In [3]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

In [4]:
data = [[-1,2],[-0.5,6],[0,10],[1,18]]
data = pd.DataFrame(data)

In [5]:
data

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [6]:
scaler = MinMaxScaler()
scaler = scaler.fit(data)
result = scaler.transform(data)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [7]:
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [8]:
scaler.inverse_transform(result)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [9]:
data = [[-1,2],[-0.5,6],[0,10],[1,18]]
scaler = MinMaxScaler(feature_range=[5,10])
result = scaler.fit_transform(data)
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [10]:
data = [[-1,2],[-0.5,6],[0,10],[1,18]]
X = np.array(data)
X

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [11]:
X_dr = (X - X.min())/(X.max()-X.min())
X_dr

array([[0.        , 0.15789474],
       [0.02631579, 0.36842105],
       [0.05263158, 0.57894737],
       [0.10526316, 1.        ]])

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()
scaler = scaler.fit(data)
result = scaler.transform(data)
result

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [15]:
scaler.mean_

array([-0.125,  9.   ])

In [16]:
scaler.var_

array([ 0.546875, 35.      ])

In [17]:
result.mean()

0.0

In [18]:
result.std()

1.0

In [19]:
scaler.inverse_transform(result)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

归一化对异常值比较敏感，大多数时候都用标准差，归一化和标准差都对缺失值忽略不计

In [1]:
import pandas as pd
data = pd.read_csv(r"D:\titanic\Narrativedata.csv",index_col=0)
data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         714 non-null float64
Sex         891 non-null object
Embarked    889 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [32]:
data.isnull().sum()

Age         177
Sex           0
Embarked      2
Survived      0
dtype: int64

In [2]:
Age = data.loc[:,"Age"].values.reshape(-1,1)

In [34]:
Age[:20]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [nan],
       [54.],
       [ 2.],
       [27.],
       [14.],
       [ 4.],
       [58.],
       [20.],
       [39.],
       [14.],
       [55.],
       [ 2.],
       [nan],
       [31.],
       [nan]])

In [3]:
from sklearn.impute import SimpleImputer

In [4]:
imp_mean = SimpleImputer()
imp_median = SimpleImputer(strategy="median")
imp_0 = SimpleImputer(strategy="constant",fill_value=0)

In [5]:
imp_mean = imp_mean.fit_transform(Age)
imp_median = imp_median.fit_transform(Age)
imp_0 = imp_0.fit_transform(Age)

In [6]:
data.loc[:,"Age"] = imp_median
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         891 non-null float64
Sex         891 non-null object
Embarked    889 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [7]:
Embarked = data.loc[:,"Embarked"].values.reshape(-1,1)

In [8]:
imp_mode = SimpleImputer(strategy="most_frequent")
data.loc[:,"Embarked"] = imp_mode.fit_transform(Embarked)

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 5 columns):
Age         891 non-null float64
Sex         891 non-null object
Embarked    891 non-null object
Survived    891 non-null object
median      891 non-null float64
dtypes: float64(2), object(3)
memory usage: 41.8+ KB


In [43]:
# 用numpy进行填补
# data.loc[:,"Age"] = data.loc[:,"Age"].fillna(data.loc[:,"Age"].median())
# data.dropna(axis=0,inplace=True)
# data.dropna(axis=1,inplace=True)
# data.drop(["Age","Embarked"],axis=1,inplace=True)

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [12]:
# data.drop(["median"],axis=1,inplace=True)

In [13]:
y = data.iloc[:,-1]
y.head()

0     No
1    Yes
2    Yes
3    Yes
4     No
Name: Survived, dtype: object

In [14]:
le = LabelEncoder()
le =le. fit(y)
label = le.transform(y)
label

array([0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       2, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 0, 2,
       2, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 0,
       0, 2, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0,
       1, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0,
       2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1,
       0, 0, 1, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2,

In [15]:
le.classes_

array(['No', 'Unknown', 'Yes'], dtype=object)

In [16]:
data.iloc[:,-1] = label

In [17]:
data.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [18]:
from sklearn.preprocessing import OrdinalEncoder

In [19]:
data_ = data.copy()

In [20]:
data_.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [21]:
data_.iloc[:,1:-1].head()

Sex Embarked
0    male        S
1  female        C
2  female        S
3  female        S
4    male        S

In [22]:
OrdinalEncoder().fit(data_.iloc[:,1:-1]).categories_

[array(['female', 'male'], dtype=object), array(['C', 'Q', 'S'], dtype=object)]

In [23]:
data_.iloc[:,1:-1] = OrdinalEncoder().fit_transform(data_.iloc[:,1:-1])

In [24]:
data_.head()

Age  Sex  Embarked  Survived
0  22.0  1.0       2.0         0
1  38.0  0.0       0.0         2
2  26.0  0.0       2.0         2
3  35.0  0.0       2.0         2
4  35.0  1.0       2.0         0

In [25]:
from sklearn.preprocessing import OneHotEncoder
X = data_.iloc[:,1:-1]

In [26]:
enc = OneHotEncoder(categories="auto").fit(X)
result = enc.transform(X).toarray()
result

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [27]:
enc.get_feature_names()

array(['x0_0.0', 'x0_1.0', 'x1_0.0', 'x1_1.0', 'x1_2.0'], dtype=object)

In [28]:
newdata = pd.concat([data,pd.DataFrame(result)],axis=1)
newdata.head()

Age     Sex Embarked  Survived    0    1    2    3    4
0  22.0    male        S         0  0.0  1.0  0.0  0.0  1.0
1  38.0  female        C         2  1.0  0.0  1.0  0.0  0.0
2  26.0  female        S         2  1.0  0.0  0.0  0.0  1.0
3  35.0  female        S         2  1.0  0.0  0.0  0.0  1.0
4  35.0    male        S         0  0.0  1.0  0.0  0.0  1.0

In [29]:
newdata.drop(["Sex","Embarked"],axis=1,inplace=True)

In [30]:
data_ = newdata
data_.head()

Age  Survived    0    1    2    3    4
0  22.0         0  0.0  1.0  0.0  0.0  1.0
1  38.0         2  1.0  0.0  1.0  0.0  0.0
2  26.0         2  1.0  0.0  0.0  0.0  1.0
3  35.0         2  1.0  0.0  0.0  0.0  1.0
4  35.0         0  0.0  1.0  0.0  0.0  1.0

根据阈值将连续型变量二值化

In [31]:
data_2 = newdata.copy()

In [32]:
from sklearn.preprocessing import Binarizer

In [33]:
X = data_2.iloc[:,0].values.reshape(-1,1)
X

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [28.  ],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [28.  ],
       [31.  ],
       [28.  ],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [28.  ],
       [19.  ],
       [28.  ],
       [28.  ],
       [40.  ],
       [28.  ],
       [28.  ],
       [66.  ],
       [28.  ],
       [42.  ],
       [28.  ],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [28.  ],
       [ 3.  ],
       [19.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [28.  ],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [

In [34]:
transformer = Binarizer(threshold=30).fit_transform(X)

In [35]:
data_2.iloc[:,0] = transformer

In [36]:
data_2.head()

Age  Survived    0    1    2    3    4
0  0.0         0  0.0  1.0  0.0  0.0  1.0
1  1.0         2  1.0  0.0  1.0  0.0  0.0
2  0.0         2  1.0  0.0  0.0  0.0  1.0
3  1.0         2  1.0  0.0  0.0  0.0  1.0
4  1.0         0  0.0  1.0  0.0  0.0  1.0

In [37]:
# 分箱
from sklearn.preprocessing import KBinsDiscretizer

In [39]:
X = data.iloc[:,0].values.reshape(-1,1)

In [40]:
data.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [41]:
est = KBinsDiscretizer(n_bins=3,encode="ordinal",strategy="uniform")

In [42]:
est.fit_transform(X)

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

In [44]:
set(est.fit_transform(X).ravel())

{0.0, 1.0, 2.0}

In [47]:
est = KBinsDiscretizer(n_bins=3,encode="onehot",strategy="uniform")

In [48]:
est.fit_transform(X).toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [50]:
import numpy as np
import pandas as pd
data = pd.read_csv(r"D:\titanic\digit_recognizor.csv")
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [51]:
data.shape

(42000, 785)

In [52]:
X = data.iloc[:,1:]  # 特征
y = data.iloc[:,0]   # 标签

In [53]:
X.shape

(42000, 784)

In [54]:
from sklearn.feature_selection import VarianceThreshold

In [55]:
selector = VarianceThreshold()

In [56]:
X_var0 = selector.fit_transform(X)

In [58]:
pd.DataFrame(X_var0).head()

0    1    2    3    4    5    6    7    8    9    ...  698  699  700  701  \
0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   702  703  704  705  706  707  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 708 columns]

In [59]:
X_var0.shape

(42000, 708)

In [60]:
X_fsvar = VarianceThreshold(np.median(X.var().values)).fit_transform(X)

In [61]:
X_fsvar.shape

(42000, 392)

In [62]:
from sklearn.ensemble import RandomForestRegressor as RFR
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.model_selection import cross_val_score
import numpy as np

In [63]:
# X = data.iloc[:,1:]
# y = data.iloc[:,0]

# X_fsvar = VarianceThreshold(np.median(X.var().values)).fit_transform(X)

# cross_val_score(KNN(),X,y,cv=5).mean()
# cross_val_score(KNN(),X_fsvar,y,cv=5).mean()
# cross_val_score(RFR(n_estimators=10,random_state=0),X,y,cv=5).mean()
# cross_val_score(RFR(n_estimators=10,random_state=0),X_fsvar,y,cv=5).mean()
# 过滤法主要的对象是需要遍历特征或需要升维的对象们，在维持算法表现的前提下，帮助算法降低计算成本。

In [64]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.model_selection import cross_val_score

In [65]:
X_fschi = SelectKBest(chi2,k=300).fit_transform(X_fsvar,y)

In [66]:
X_fschi.shape

(42000, 300)

In [68]:
cross_val_score(RandomForestClassifier(n_estimators=10,random_state=0),X_fschi,y,cv=5).mean()

0.9333098667649198

In [ ]:
# # 画学习曲线探索k的最佳取值
# import matplotlib.pyplot as plt
# score = []
# for i in range(200,400,20):
#     X_fschi = SelectKBest(chi2,k=i).fit_transform(X_fsvar,y)
#     score_e = cross_val_score(RandomForestClassifier(n_estimators=10,random_state=0),X_fschi,y,cv=5).mean()
#     score.append(score_e)
    
# plt.figure(figsize=[20,5])
# plt.plot(range(200,400,20),score)
# plt.show()

In [72]:
chivalue,pvalue_chi = chi2(X_fsvar,y)

In [73]:
chivalue.shape[0]

392

In [74]:
(pvalue_chi > 0.5).sum()

0

In [75]:
k = chivalue.shape[0] - (pvalue_chi > 0.5).sum()

In [77]:
X_fschi = SelectKBest(chi2,k=(chivalue.shape[0]-(pvalue_chi > 0.5).sum())).fit_transform(X_fsvar,y)
cross_val_score(RandomForestClassifier(n_estimators=10,random_state=0),X_fschi,y,cv=10).mean()

0.9411198132299345

In [78]:
from sklearn.feature_selection import f_classif

In [79]:
F,pvalues_f = f_classif(X_fsvar,y)

In [80]:
k = F.shape[0] - (pvalues_f > 0.05).sum()

In [81]:
k

392

In [82]:
X_fsF = SelectKBest(f_classif,k=(F.shape[0]-(pvalues_f > 0.05).sum())).fit_transform(X_fsvar,y)
cross_val_score(RandomForestClassifier(n_estimators=10,random_state=0),X_fsF,y,cv=5).mean()

0.9388098166696807

In [84]:
from sklearn.feature_selection import mutual_info_classif as MIC

In [86]:
result = MIC(X_fsvar,y)
(result>0).sum()

392

In [87]:
k = result.shape[0] - (result <= 0).sum()

In [92]:
k

392

In [89]:
X_fsF = SelectKBest(MIC,k = (result.shape[0]-(result <= 0).sum())).fit_transform(X_fsvar,y)
cross_val_score(RandomForestClassifier(n_estimators=10,random_state=0),X_fsF,y,cv=10).mean()

0.9411198132299345

In [90]:
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier as RFC

In [93]:
RFC_ = RFC(n_estimators=10,random_state=0)

In [94]:
X_embedded = SelectFromModel(RFC_,threshold=0.005).fit_transform(X,y)

In [95]:
X_embedded.shape

(42000, 47)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
threshold = np.linspace(0,(RFC_.fit(X,y).feature_importance_).max(),20)
score_e = []
for i in threshold:
    X_embedded = SelectFromModel(RFC_,threshold=i).fit_transform(X,y)
    score_e = cross_val_score(RFC_,X_embedded,y,cv=10).mean()
    
plt.figure()
plt.plot(threshold,score_e)
plt.show()
# 嵌入法选出来的特征比方差过滤要少，时间要更短，交叉验证的结果比过滤后的结果要好